### ISSUE TITLE
parallax-inner has a bug in latest version of Google Chrome

### ISSUE THREAD

**Issue by Bram-Zijp** [TemplatemonsterPlugins/rd-parallax#3]
http://imgur.com/a/D8ogN

The images are self explanatory

**Comment by hostekevin** [comment]
Hello, 

Same issue for me, the parallax image stay in the viewport. 
I try to change z-index or padding/margin.
No issue with Firefox.

**Comment by Bram-Zijp** [comment]
Hi,

This bug appears sinse the latest version of Chrome. I removed this plugin from the template as the padding/margin removal made it bug while scrolling.

**Comment by hostekevin** [comment]
Hey @Bram-Zijp ,

I fork this repo and try to resolve the issue : try with my own copy [github.com/Kevkehz/rd-parallax/tree/master/dist/js](https://github.com/Kevkehz/rd-parallax/tree/master/dist/js) 

It seems to work with a line comment about webkit "amend".

**Comment by Mnemon1k** [comment]
We fix this issue in RD Parallax 3.6.5.
